import streamlit as st
st.title("My Biodata")
st.header("Personal Information")
name=st.text_input("Full Name","Mohan Raj")
age=st.number_input("Age", min_value=1, max_value=100, value=25)
gender=st.selectbox("Gender",["Male", "Female", "Others"])
dob=st.date_input("Data of Birth")
st.header("Contact Information")
email=st.text_input("Email","mohan@example.com")
phone=st.text_input("Phone Number","+91-1234567891")
address=st.text_area("Address","123,Main Street,City,Country")
st.header("Education")
education=st.text_area("Education Background","B.sc in Computer")
st.header("Skills")
skills=st.multiselect("Select Skill",
                      ["Python", "Machine learning","Data Analysis","Web Development","Communication"],
                                      default=["Select your skills"])
st.header("📝 Biodata Summary")
if st.button("Generate Biodata"):
    st.subheader("Here’s Your Biodata:")
    st.write(f"*Name:* {name}")
    st.write(f"*Age:* {age}")
    st.write(f"*Gender:* {gender}")
    st.write(f"*Date of Birth:* {dob}")
    st.write(f"*Email:* {email}")
    st.write(f"*Phone:* {phone}")
    st.write(f"*Address:* {address}")
    st.write(f"*Education:* {education}")
    st.write(f"*Skills:* {', '.join(skills)}")
  
